apiVersion: v1
kind: Secret
metadata:
  name: voteapp-postgresql-secret
  namespace: vote-app-ns
  labels:
    cnpg.io/reload: ""
type: kubernetes.io/basic-auth
data:
  password: dm90ZWFwcDEyMw==
  username: dm90ZWFwcA==
---
apiVersion: v1
kind: Secret
metadata:
  name: voteapp-db-secret
  namespace: vote-app-ns
type: Opaque
data:
  DB_CONNECTION_STRING: cG9zdGdyZXM6Ly92b3RlYXBwOnZvdGVhcHAxMjNAdm90ZWFwcC1wb3N0Z3Jlcy1ydy9wb3N0Z3Jlcw==
