apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: registry.sample.local/library/examplevotingapp_worker
        name: worker
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: voteapp-dotnet-db-secret
              key: DB_CONNECTION_STRING
